<?php

declare(strict_types=1);

namespace App\Random\Generators\Equations;

use App\Random\Equations\Expr;
use App\Random\Equations\Node;
use App\Random\Equations\Problem;
use App\Random\Generators\Params;
use App\Random\Generators\ParamSchema;
use App\Random\Rng\Rng;

/**
 * Derivatives and integrals, both generated by differentiating.
 *
 * Differentiation is closed over this module's function set: every rule — power,
 * product, quotient, chain, and the standard table — takes an expression the AST
 * can hold and returns another one. So a derivative problem is generated
 * forwards, differentiated symbolically, and the answer is exact because it was
 * computed rather than guessed at.
 *
 * Integration is not closed. `e^{x²}` has no elementary antiderivative, and
 * neither does the overwhelming majority of what a grammar would hand you if it
 * generated an integrand and then went looking for one. **So the integral mode
 * generates the antiderivative F first and presents F′ as the problem.** The
 * hard direction is never travelled: every integral this generator offers is
 * solvable because its solution is what it was built out of, and the answer key
 * is F by construction.
 *
 * That inversion is the only reason this module can offer integrals at all.
 */
final class CalculusGenerator extends EquationsGenerator
{
    /** Candidate points for the answer key's numerical check, all in the domain of ln and √. */
    private const SAFE_POINTS = [1.3, 0.9, 1.7, 0.7, 2.1, 1.1, 2.4];

    public function key(): string
    {
        return 'equations.calculus';
    }

    public function name(): string
    {
        return 'Calculus';
    }

    public function tagline(): string
    {
        return 'Derivatives and integrals per rule — the integrals exist because they were built backwards.';
    }

    public function schema(): ParamSchema
    {
        return ParamSchema::make()
            ->enum('mode', 'Mode', [
                'derivative' => 'Differentiate',
                'integral' => 'Integrate',
            ], default: 'derivative')
            ->enum('rule', 'Rule', [
                'power' => 'Power rule',
                'product' => 'Product rule',
                'quotient' => 'Quotient rule',
                'chain' => 'Chain rule',
                'trig' => 'Trigonometric',
                'exp_log' => 'Exponential and logarithmic',
                'mixed' => 'Mixed',
            ], default: 'mixed')
            ->int('count', 'How many', default: 6, min: 1, max: 40);
    }

    public function problems(Rng $rng, Params $params): array
    {
        $mode = $params->string('mode');
        $rule = $params->string('rule');
        $problems = [];

        for ($i = 0; $i < $params->int('count'); $i++) {
            $chosen = $rule === 'mixed'
                ? $rng->pick(['power', 'product', 'quotient', 'chain', 'trig', 'exp_log'])
                : $rule;

            $problems[] = $mode === 'integral'
                ? $this->integral($rng, $chosen)
                : $this->derivative($rng, $chosen);
        }

        return $problems;
    }

    private function derivative(Rng $rng, string $rule): Problem
    {
        $f = $this->template($rng, $rule, 'derivative');
        $answer = $f->derive('x')->simplify();

        return new Problem(
            prompt: 'd/dx [ '.$f->toPlain().' ]',
            promptLatex: '\frac{d}{dx}\left[\, '.$f->toLatex().' \,\right]',
            answer: $answer->toPlain(),
            answerLatex: $answer->toLatex(),
            extra: ['rule' => $rule],
            check: [
                'mode' => 'derivative',
                'function' => $f,
                'answer' => $answer,
                'point' => $this->safePoint($f, $answer),
            ],
        );
    }

    private function integral(Rng $rng, string $rule): Problem
    {
        $antiderivative = $this->template($rng, $rule, 'integral');
        $integrand = $antiderivative->derive('x')->simplify();

        return new Problem(
            prompt: '∫ '.$integrand->toPlain().' dx',
            promptLatex: '\int '.$integrand->toLatex().' \,dx',
            answer: $antiderivative->toPlain().' + C',
            answerLatex: $antiderivative->toLatex().' + C',
            extra: ['rule' => $rule],
            check: [
                'mode' => 'integral',
                'function' => $integrand,
                'answer' => $antiderivative,
                'point' => $this->safePoint($integrand, $antiderivative),
            ],
        );
    }

    /**
     * Where the answer can be checked numerically.
     *
     * Not a fixed constant: a quotient template can put a pole anywhere, and a
     * verification point that lands on one would report a disagreement between
     * two expressions that agree everywhere they are defined.
     */
    private function safePoint(Node $f, Node $answer): float
    {
        foreach (self::SAFE_POINTS as $point) {
            $values = [
                $f->evaluate(['x' => $point]),
                $answer->evaluate(['x' => $point]),
                // The finite-difference check straddles the point, so both sides
                // of it have to be usable too.
                $f->evaluate(['x' => $point + 1e-4]),
                $f->evaluate(['x' => $point - 1e-4]),
            ];

            foreach ($values as $value) {
                if (! is_finite($value) || abs($value) > 1e6) {
                    continue 2;
                }
            }

            return $point;
        }

        return self::SAFE_POINTS[0];
    }

    /**
     * The shape a problem is grown from.
     *
     * Templates rather than the free grammar, because a derivative question is
     * about one technique at a time: "differentiate this product" stops being a
     * product-rule exercise the moment the grammar hangs a nested quotient off
     * one of the factors.
     */
    private function template(Rng $rng, string $rule, string $mode): Node
    {
        $x = Expr::v('x');

        return match ($rule) {
            'product' => $this->product($rng, $x),
            'quotient' => $mode === 'integral' ? $this->reciprocal($rng, $x) : $this->quotient($rng, $x),
            'chain' => $this->chain($rng, $x),
            'trig' => $this->trigonometric($rng, $x),
            'exp_log' => $this->exponential($rng, $x),
            default => $this->polynomial($rng, $mode),
        };
    }

    private function polynomial(Rng $rng, string $mode): Node
    {
        $degree = $rng->intBetween(2, 5);
        $coefficients = [$this->nonZero($rng, -6, 6)];

        for ($power = $degree - 1; $power >= 0; $power--) {
            // Zeros are allowed in the middle: a polynomial with a missing term
            // is a normal polynomial, and forcing every power to appear makes
            // every problem look like the same problem.
            $coefficients[] = $rng->intBetween(-7, 7);
        }

        // An antiderivative with a constant term of its own would print as
        // `… + 7 + C`, which is not wrong but is the answer key admitting it
        // does not know what C is for.
        if ($mode === 'integral') {
            $coefficients[count($coefficients) - 1] = 0;
        }

        return Expr::polynomial($coefficients);
    }

    private function product(Rng $rng, Node $x): Node
    {
        return $rng->pick([
            fn (): Node => Expr::mul(Expr::pow($x, Expr::n($rng->intBetween(2, 3))), Expr::sin($x)),
            fn (): Node => Expr::mul($x, Expr::cos($x)),
            fn (): Node => Expr::mul($x, Expr::exp($x)),
            fn (): Node => Expr::mul($x, Expr::ln($x)),
            fn (): Node => Expr::mul(
                Expr::add(Expr::scale($this->nonZero($rng, 2, 5), $x), Expr::n($this->nonZero($rng, -6, 6))),
                Expr::sin($x),
            ),
            fn (): Node => Expr::mul(Expr::exp($x), Expr::cos($x)),
        ])();
    }

    private function quotient(Rng $rng, Node $x): Node
    {
        return $rng->pick([
            fn (): Node => Expr::div(
                Expr::add(Expr::scale($this->nonZero($rng, 2, 6), $x), Expr::n($this->nonZero($rng, -7, 7))),
                Expr::add($x, Expr::n($rng->intBetween(2, 7))),
            ),
            fn (): Node => Expr::div(Expr::pow($x, Expr::n($rng->intBetween(2, 3))), Expr::add($x, Expr::n($rng->intBetween(2, 6)))),
            fn (): Node => Expr::div(Expr::sin($x), $x),
            fn (): Node => Expr::div(Expr::exp($x), Expr::add(Expr::pow($x, Expr::n(2)), Expr::n(1))),
        ])();
    }

    /**
     * For the integral side, the quotient rule reads backwards: the things whose
     * derivatives are quotients are logarithms and reciprocals, and those are
     * exactly the integrals a student is asked for.
     */
    private function reciprocal(Rng $rng, Node $x): Node
    {
        $a = $this->nonZero($rng, 2, 6);
        $b = $rng->intBetween(1, 8);

        return $rng->pick([
            fn (): Node => Expr::ln(Expr::add(Expr::scale($a, $x), Expr::n($b))),
            fn (): Node => Expr::div(Expr::n(1), Expr::add(Expr::scale($a, $x), Expr::n($b))),
            // Written as a negative power rather than as `a/xⁿ`: the quotient
            // rule on the fraction form produces a numerator of `0·xⁿ − …` that
            // simplify() can tidy but not cancel, and the power rule here gives
            // the same answer with nothing to tidy.
            fn (): Node => Expr::scale($this->nonZero($rng, 2, 9), Expr::pow($x, Expr::n(-$rng->intBetween(1, 3)))),
        ])();
    }

    private function chain(Rng $rng, Node $x): Node
    {
        // ln and √ take a strictly positive argument for every x > 0, which is
        // where the verification points live — the guard is in the coefficients,
        // not in a retry.
        $a = $rng->intBetween(2, 5);
        $b = $rng->intBetween(1, 9);
        $inner = Expr::add(Expr::scale($a, $x), Expr::n($b));

        return $rng->pick([
            fn (): Node => Expr::sin($inner),
            fn (): Node => Expr::cos($inner),
            fn (): Node => Expr::exp(Expr::scale($this->nonZero($rng, -3, 3), $x)),
            fn (): Node => Expr::pow($inner, Expr::n($rng->intBetween(2, 5))),
            fn (): Node => Expr::ln($inner),
            fn (): Node => Expr::sqrt($inner),
        ])();
    }

    private function trigonometric(Rng $rng, Node $x): Node
    {
        $a = $this->nonZero($rng, -7, 7);
        $b = $this->nonZero($rng, -7, 7);
        $k = $rng->intBetween(2, 4);

        return $rng->pick([
            fn (): Node => Expr::add(Expr::scale($a, Expr::sin($x)), Expr::scale($b, Expr::cos($x))),
            fn (): Node => Expr::scale($a, Expr::sin(Expr::scale($k, $x))),
            fn (): Node => Expr::add(Expr::scale($a, Expr::cos(Expr::scale($k, $x))), Expr::scale($b, $x)),
            fn (): Node => Expr::add(Expr::scale($a, Expr::sin($x)), Expr::scale($b, $x)),
        ])();
    }

    private function exponential(Rng $rng, Node $x): Node
    {
        $a = $this->nonZero($rng, -6, 6);
        $b = $this->nonZero($rng, -6, 6);
        $k = $this->nonZero($rng, -3, 3);

        return $rng->pick([
            fn (): Node => Expr::scale($a, Expr::exp(Expr::scale($k, $x))),
            fn (): Node => Expr::add(Expr::scale($a, Expr::ln($x)), Expr::scale($b, $x)),
            fn (): Node => Expr::add(Expr::scale($a, Expr::exp($x)), Expr::scale($b, Expr::pow($x, Expr::n(2)))),
            // e^{x²} has no elementary antiderivative, so this integrand exists
            // only because it was reached by differentiating rather than by
            // integrating — the inversion, in one template.
            fn (): Node => Expr::scale($a, Expr::exp(Expr::pow($x, Expr::n(2)))),
        ])();
    }
}
